# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Report Admob

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
concurrency:
  group: report-admob
  cancel-in-progress: true
jobs:
  run-spring-boot-apllycation:

    runs-on: self-hosted
    permissions:
      contents: read
    steps:
      - name: Change User
        run: sudo chmod -R 777 .

      - uses: actions/checkout@v4

      - name: Install zip
        run: sudo apt install zip -y

      - name: Install JDK
        run: sudo apt install openjdk-17-jdk openjdk-17-jre -y

      - name: Install SDK Man && Gradle
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk version
          sdk install gradle 8.6

      - name: Make File Service
        run: | 
          sudo echo -e "[Unit]
          Description=My Spring Boot Application
          After=syslog.target
          [Service]
          User=root
          WorkingDirectory=/home/ubuntu/actions-runner/_work/pass-gpt/pass-gpt
          ExecStart=/home/ubuntu/.sdkman/candidates/gradle/current/bin/gradle Bootrun
          SuccessExitStatus=143
          Restart=always
          RestartSec=0
          [Install]
          WantedBy=multi-user.target" | sudo tee /etc/systemd/system/spring.service

      - name: Spring Boot
        run: |
          sudo systemctl daemon-reload
          sudo systemctl restart spring
          sudo systemctl status spring
          sudo systemctl enable spring
